app/ReportingImage/Controllers/DipcadClaimPendingController.cs
using Ionic.Zip;
using iTextSharp.text;
using ReportingImage.Models;
using ReportingImage.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ReportingImage.Controllers
{
    public class DipcadClaimPendingController : Controller
    {
        
        ReportingImageEntities _db = new ReportingImageEntities();
        GetSession MeGetSession = new GetSession();
        string thisMenu = "Pending";

        // GET: DipcadClaimPending
        public ActionResult Index(string policyNumber, string ddlCategory, int pageNumber = 1, string receiveddatefrom = null, string receiveddateto = null)
        {

            var User = GetSession.UserName();
            TempData["ddlCategory"] = ddlCategory;

            var tempResult = _db.SPCLM_PolicyPool_Inq().Where(x => User == x.UserAssign?.Trim() 
                                                                && (x.IsPending == true)
                                                                ).ToList();
            //var tempResult = new List<PolicyPool_Pending_inq>();
            //DataTable dTab = Common.ExecuteQuery($"dbo.SPCLM_PolicyPool_Inq_dev");
            //for (int i = 0; i < dTab.Rows.Count; i++)
            //{
            //    if (dTab.Rows[i]["IsPending"].ToString() != "" && dTab.Rows[i]["UserAssign"].ToString().Trim() == User)
            //    {
            //        var data = new PolicyPool_Pending_inq();
            //        data.CaseId = Convert.ToInt64(dTab.Rows[i]["CaseId"].ToString());
            //        data.PolicyNo = dTab.Rows[i]["PolicyNo"].ToString();
            //        data.Source = dTab.Rows[i]["Source"].ToString();
            //        data.WorkType = dTab.Rows[i]["WorkType"].ToString();
            //        data.Category = dTab.Rows[i]["Category"].ToString();
            //        data.RLSTRANS = dTab.Rows[i]["RLSTRANS"].ToString();
            //        data.RLSCaptureDate = String.IsNullOrWhiteSpace(dTab.Rows[0]["RLSCaptureDate"].ToString()) ? (DateTime?)null : Convert.ToDateTime(dTab.Rows[0]["RLSCaptureDate"].ToString());
            //        data.IsComplete = dTab.Rows[0]["IsComplete"].ToString() == "1" ? true : false;
            //        data.IsPending = dTab.Rows[0]["IsPending"].ToString() == "1" ? true : false;
            //        data.CompleteDate = String.IsNullOrWhiteSpace(dTab.Rows[0]["CompleteDate"].ToString()) ? (DateTime?)null : Convert.ToDateTime(dTab.Rows[0]["CompleteDate"].ToString());
            //        data.CreatedDate = String.IsNullOrWhiteSpace(dTab.Rows[0]["CreatedDate"].ToString()) ? (DateTime?)null : Convert.ToDateTime(dTab.Rows[0]["CreatedDate"].ToString());
            //        data.ReceivedDate = String.IsNullOrWhiteSpace(dTab.Rows[0]["ReceivedDate"].ToString()) ? (DateTime?)null : Convert.ToDateTime(dTab.Rows[0]["ReceivedDate"].ToString());
            //        data.UserAssign = dTab.Rows[i]["UserAssign"].ToString();
            //        data.Remarks = dTab.Rows[i]["Message"].ToString();
            //        tempResult.Add(data);
            //    }                
            //}

            //if (tempResult.Count > 0)
            //{
            //    tempResult = tempResult.Where(a => a.IsPending == true).ToList();
            //}

            if (receiveddatefrom != null && receiveddatefrom != "")
            {
                DateTime dateTimereceiveddatefrom = Convert.ToDateTime(receiveddatefrom);
                tempResult = tempResult.Where(a => a.CreatedDate.Date >= dateTimereceiveddatefrom).ToList();
            }
            if (receiveddateto != null && receiveddateto != "")
            {
                DateTime dateTimereceiveddateto = Convert.ToDateTime(receiveddateto);
                tempResult = tempResult.Where(a => a.CreatedDate.Date <= dateTimereceiveddateto).ToList();
            }
            if (policyNumber != null && policyNumber != "")
            {
                //tempResult = _db.SPCLM_PolicyPool_Inq().Where(a => a.PolicyNo == policyNumber).ToList();
                tempResult = tempResult.Where(a => a.PolicyNo == policyNumber).ToList();
            }

            foreach (var item in tempResult)
            {
                if (item.VIP == "YES") item.ColorSLA = "#f78181";
            }

            ViewBag.ListPolicyPool = tempResult;

            List<SelectListItem> dataCategory = new List<SelectListItem>();
            dataCategory.Add(new SelectListItem() { Text = "ALL", Value = "ALL" });
            dataCategory.Add(new SelectListItem() { Text = "New Case", Value = "New Case" });
            dataCategory.Add(new SelectListItem() { Text = "Jawaban Pending", Value = "Jawaban Pending" });
            ViewBag.ddlCategory = new SelectList(dataCategory, "Value", "Text", ddlCategory);

            _db.zsp_AuditTrailInsert("Claim Open Policy List", policyNumber, GetSession.UserName());

            return View();
        }

        // GET: DipcadClaimOpen/Details/5
        public ActionResult DetailClient(int? caseid)
        {
            if (caseid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string[] wType;

            var userName = GetSession.UserName();

            DipcadClaimOpenViewModels singleCLMOpen = GetListCLMbyID(caseid);

            if (singleCLMOpen == null)
            { return HttpNotFound(); }

            #region 'List'
            string dllCategoryVal = singleCLMOpen.CATEGORY;
            string dllWorktypeVal = singleCLMOpen.WORKTYPE;
            string dllPriorityVal = singleCLMOpen.PRIORITY;
            if (singleCLMOpen.VIP == "YES")
                dllPriorityVal = "3";
            //string dllCaseTypeVal = singleCLMOpen.CASE_TYPE;
            string dllPeReasonVal = singleCLMOpen.PENDING_REASON;
            //string dllAsignTo = getUserAssign(caseid);
            //string dllAsignTo = getUserAssign(singleCLMOpen.WORKTYPE);

            TempData["ddlWorktype"] = dllWorktypeVal;
            TempData["ddlCategory"] = dllCategoryVal;
            //TempData["AssignTo"] = dllAsignTo;

            List<SelectListItem> dataWorkType = new List<SelectListItem>();
            var workTypeList = GetListWorkType();
            dataWorkType.Add(new SelectListItem() { Text = "", Value = "" });
            if (workTypeList != null)
            {
                foreach (string item in workTypeList)
                {
                    wType = item.Split('|');
                    dataWorkType.Add(new SelectListItem() { Text = wType[1], Value = wType[0] });
                }
            }
            string[] reasonType;
            List<SelectListItem> dataReasonPending = new List<SelectListItem>();
            var pendingReasonList = GetReferenceData("ReasonPending");
            dataReasonPending.Add(new SelectListItem() { Text = "", Value = "" });
            if (pendingReasonList != null)
            {
                foreach (string item in pendingReasonList)
                {
                    reasonType = item.Split('|');
                    dataReasonPending.Add(new SelectListItem() { Text = reasonType[1], Value = reasonType[0] });
                }
            }
            string[] assignOtherDiv;
            List<SelectListItem> dataOtherDiv = new List<SelectListItem>();
            var otherDivList = GetReferenceData("AssignToOtherDiv");
            dataOtherDiv.Add(new SelectListItem() { Text = "", Value = "" });
            if (otherDivList != null)
            {
                foreach (string item in otherDivList)
                {
                    assignOtherDiv = item.Split('|');
                    dataOtherDiv.Add(new SelectListItem() { Text = assignOtherDiv[1], Value = assignOtherDiv[0] });
                }
            }
            string[] priority;
            List<SelectListItem> dataPriority = new List<SelectListItem>();
            var priorityList = GetReferenceData("Priority");
            dataPriority.Add(new SelectListItem() { Text = "", Value = "" });
            if (priorityList != null)
            {
                foreach (string item in priorityList)
                {
                    priority = item.Split('|');
                    dataPriority.Add(new SelectListItem() { Text = priority[1], Value = priority[0] });
                }
            }
            //string[] caseType;
            //List<SelectListItem> dataCaseType = new List<SelectListItem>();
            //var caseTypeList = GetReferenceData("CaseType");
            //dataCaseType.Add(new SelectListItem() { Text = "", Value = "" });
            //if (caseTypeList != null)
            //{
            //    foreach (string item in caseTypeList)
            //    {
            //        caseType = item.Split('|');
            //        dataCaseType.Add(new SelectListItem() { Text = caseType[1], Value = caseType[0] });
            //    }
            //}

            ViewBag.dllWorktype = new SelectList(dataWorkType, "Value", "Text", dllWorktypeVal);
            ViewBag.dllPenReasonList = new SelectList(dataReasonPending, "Value", "Text", dllPeReasonVal);
            ViewBag.dllOtherDiv = new SelectList(dataOtherDiv, "Value", "Text");
            ViewBag.dllPriority = new SelectList(dataPriority, "Value", "Text", dllPriorityVal);
            //ViewBag.dllCaseType = new SelectList(dataCaseType, "Value", "Text", dllCaseTypeVal);

            List<SelectListItem> dataCategory = new List<SelectListItem>();
            dataCategory.Add(new SelectListItem() { Text = "New Case", Value = "New Case" });
            dataCategory.Add(new SelectListItem() { Text = "Jawaban Pending", Value = "Jawaban Pending" });
            ViewBag.dllCategory = new SelectList(dataCategory, "Value", "Text", dllCategoryVal);

            List<SelectListItem> dataAssignTo = new List<SelectListItem>();

app/ReportingImage/Views/DipcadClaimPending/ImagesClient.cshtml
@model ReportingImage.ViewModels.DipcadClaimListImageViewModel

@{
    ViewBag.Title = "Detail Image";
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-warning">
        <p><strong>Error:</strong> @TempData["Error"].ToString()</p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @TempData["Success"].ToString()
    </div>
}

@using (Html.BeginForm("ImagesClient", "DipcadClaimPending", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-6">List Images</div>
                <div class="col-lg-6" style="text-align:right">
                    <a data-toggle="modal" href="@Url.Action("Index","DipcadClaimPending")" class="btn btn-primary"><i class="fa fa-backward"></i> Back </a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">

                <div class="col-md-2">
                    <input id="btnAddImage" class="btn btn-primary" value="Add Image" type="button" data-toggle="modal" data-target="#myModal" />@*onclick="return ValidationSubmit()" />*@
                </div>

                <div id='myModal' class='modal fade' role="dialog" style="width:unset; background-color: transparent">
                    <div class="modal-dialog" style="width:800px">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title" style="background-color:none">Preview Content</h4>
                            </div>
                            <div class="modal-body">
                                @{
                                    <div class="row" style="margin-top:10px">
                                        <div class="col-md-3" style="text-align:right">
                                            Document Type
                                        </div>
                                        <div class="col-md-9">
                                            @Html.DropDownList("dllDocType", (SelectList)ViewBag.dllDocType, htmlAttributes: new { @class = "form-control", @placeholder = "-- Select --" })
                                            <label id="errorDocumentType" class="text-danger" hidden="hidden">This field is required</label>
                                        </div>
                                    </div>

                                    <div class="row" style="margin-top:10px">
                                        <div class="col-md-3" style="text-align:right">
                                            Description
                                        </div>
                                        <div class="col-md-9">
                                            @*@Html.DropDownList("ddlDocumentType", (SelectList)ViewBag.dllDocumentType, new { @class = "form-control" })*@
                                            @Html.TextBox("description", new { @class = "form-control", @placeholder = "Description", })
                                            @*@Html.TextBoxFor(model => model.CLAIMNO, new { @class = "form-control" })*@
                                            <label id="errorDocumentType" class="text-danger" hidden="hidden">This field is required</label>
                                        </div>
                                    </div>

                                    <div class="row" style="margin-top:10px">
                                        <div class="col-md-3" style="text-align:right">
                                            Chosse File
                                        </div>
                                        <div class="col-md-9">
                                            @Html.TextBox("mdlImageFile", null, new { @type = "file", @name = "File", @accept = ".pdf,.jpg,.jpeg,.tiff,.tif" })
                                            <label id="errorImageFile" class="text-danger" hidden="hidden">This field is required</label>
                                        </div>
                                    </div>
                                }
                                <div class="row" style="margin-top:10px">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Add Image" name="Submit" class="btn btn-primary" />@*id="btnModalSubmit"*@ @*onclick="return ValidationModel()" />*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-12">
                    <table width="100%" style="font-size:12px" class="table table-striped table-bordered table-hover" id="dataTable-example">
                        <thead>
                            <tr>
                                <th><input type="checkbox" onchange="checkAll(this)" /></th>
                                <th>@Html.DisplayName("File Name")</th>
                                <th>@Html.DisplayName("Document Name")</th>
                                <th>@Html.DisplayName("Description")</th>
                                <th>@Html.DisplayName("Create Date")</th>
                                <th>@Html.DisplayName("Source")</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.DetailImageViewModels.Count; ++i)
                            {
                                <tr>
                                    <td>
                                        @Html.CheckBoxFor(x => x.DetailImageViewModels[i].Checked)
                                        @Html.HiddenFor(x => x.DetailImageViewModels[i].PolicyNumber)
                                    </td>
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILENAME)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILEIMAGE_temp)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].Extension)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].DocumentName)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].Source)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILENAMEORIGIN)
                                    <td>
                                        <button class="btn btn-default" type="button" data-toggle="modal" data-target="#@Model.DetailImageViewModels[i].PreviewContentId">
                                            @Model.DetailImageViewModels[i].FILENAME
                                        </button>

                                        <!--MODAL Show File-->
                                        <div id="@Model.DetailImageViewModels[i].PreviewContentId" class="modal fade" role="dialog" style="width:unset; background-color: transparent">
                                            <div class="modal-dialog" style="width:800px">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        <h4 class="modal-title" style="background-color:none">Preview Content</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        @if (Model.DetailImageViewModels[i].Extension == "application/pdf")
                                                        {
                                                            <object type="@Model.DetailImageViewModels[i].Extension" data="@Model.DetailImageViewModels[i].FilePath"
                                                                    width="750" height="500"></object>
                                                        }
                                                        else
                                                        {
                                                            <img src="@Model.DetailImageViewModels[i].FilePath"
                                                                 width="750" height="500" />
                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].DocumentName)</td>

                                     <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].Description)</td>

                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].CreatedDate)</td>

                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].Source)</td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <!--Button Download-->
            @Html.HiddenFor(x => x.Case_ID)
            @Html.HiddenFor(x => x.PolicyNumber)
            @Html.HiddenFor(x => x.WorkType_id)
            <div class="row">
                <div class="col-lg-12">
                    <div class="box-footer">
                        <button id="btnSubmit" type="submit" class="btn btn-default"><i class="fa fa-download"></i> Download Zip File</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/CountDown/countdown.login.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTable-example').DataTable({
            responsive: true,
            paging: false
        });
    });

    function checkAll(elm) {
        var checkBoxes = document.getElementsByTagName('input');
        if (elm.checked) {
            for (var i = 0; i < checkBoxes.length; i++) {
                if (checkBoxes[i].type == 'checkbox') {
                    checkBoxes[i].checked = true;
                }
            }
        }
        else {
            for (var i = 0; i < checkBoxes.length; i++) {
                if (checkBoxes[i].type == 'checkbox') {
                    checkBoxes[i].checked = false;
                }
            }
        }
    };
</script>

app/ReportingImage/Views/DipcadClaimPending/Index.cshtml
@model ReportingImage.ViewModels.PagedList<ReportingImage.ViewModels.DipcadClaimOpenViewModels>

@{
    ViewBag.Title = "Dipcad Claim Pending List";
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-warning">
        <p><strong>Error:</strong> @TempData["Error"].ToString()</p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @TempData["Success"].ToString()
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">

        <div class="panel-heading">
            <div class="row" style="margin-top:10px">
                <div class="col-lg-2">
                    Created Date From
                </div>
                <div class="col-lg-4">
                    <div id="dtreceiveddatefrom" class="input-group">
                        @Html.TextBox("receiveddatefrom", null, new { @placeholder = "Policy Number", @class = "form-control", @type = "date", @width = "100%" })
                        <span class="input-group-addon add-on ">
                            <i data-time-icon="fa fa-calendar" data-date-icon="fa fa-calendar"></i>
                        </span>
                    </div>
                </div>
                <div class="col-lg-2">
                    Created Date To
                </div>
                <div class="col-lg-4">
                    <div id="dtreceiveddateto" class="input-group">
                        @Html.TextBox("receiveddateto", null, new { @placeholder = "Policy Number", @class = "form-control", @type = "date", @width = "100%" })
                        <span class="input-group-addon add-on ">
                            <i data-time-icon="fa fa-calendar" data-date-icon="fa fa-calendar"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-lg-2">
                    Policy Number
                </div>
                <div class="col-lg-8">
                    @Html.TextBox("policyNumber", null, new { @placeholder = "Policy Number", @class = "form-control" })
                </div>
                <div class="col-lg-2">
                    <input type="submit" value="Search" class="fa fa-search btn btn-primary" style="width:100%" />
                </div>
            </div>
            <div class="row" style="margin-top:10px" hidden>
                <!-- Ryan Feb 21 : diminta agar ditutup -->
                <div class="col-lg-2">
                    Category
                </div>
                <div class="col-lg-8">
                    @Html.DropDownList("ddlCategory", (SelectList)ViewBag.ddlCategory, htmlAttributes: new { @class = "form-control", @placeholder = "-- Select --" })
                </div>
                @*<div class="col-lg-2">
                        <input type="submit" value="Search" class="fa fa-search btn btn-primary" />
                    </div>*@
            </div>
        </div>

        <!-- Panel Body  -->
        <div class="panel-body">
            <div class="row">

                <div class="col-lg-12">
                    <table width="100%"
                           style="width:100%;font-size:10px" role="grid" aria-describedby="dataTables-example_pool"
                           class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("No")
                                </th>
                                <th>
                                    @Html.DisplayName("Action")
                                </th>
                                <th>
                                    @Html.DisplayName("Case ID")
                                </th>
                                <th>
                                    @Html.DisplayName("Policy Number")
                                </th>
                                <th>
                                    @Html.DisplayName("Claim Number")
                                </th>
                                <th>
                                    @Html.DisplayName("Source")
                                </th>
                                <th>
                                    @Html.DisplayName("Work Type")
                                </th>
                                <th>
                                    @Html.DisplayName("SLA Claim")
                                </th>
                                <th>
                                    @Html.DisplayName("SLA Pending")
                                </th>
                                <th>
                                    @Html.DisplayName("User From")
                                </th>
                                <th>
                                    @Html.DisplayName("Request Pending Date")
                                </th>
                                <th>
                                    @Html.DisplayName("RLS Trans Status")
                                </th>
                                <th>
                                    @Html.DisplayName("RLS Captured Date")
                                </th>
                                <th>
                                    @Html.DisplayName("Created Date")
                                </th>
                                <th>
                                    @Html.DisplayName("Received Date")
                                </th>
                                <th>
                                    @Html.DisplayName("VIP")
                                </th>
                                <th>
                                    @Html.DisplayName("Remarks")
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int seq = 1;}
                            @foreach (var result in ViewBag.ListPolicyPool)
                            {
                                <tr style="background-color:@result.ColorSLA">
                                    <td>
                                        @seq
                                    </td>
                                    <td>
                                        <a data-toggle="tooltip" title="View"
                                           href="@Url.Action("DetailClient","DipcadClaimPending",new { caseid = result.CaseId })"
                                           class="btn btn-default">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                        <a data-toggle="tooltip" title="Image"
                                           href="@Url.Action("ImagesClient","DipcadClaimPending",new { case_id = result.CaseId })"
                                           class="btn btn-default">
                                            <i class="fa fa-file-image-o"></i>
                                        </a>
                                    </td>
                                    <td>
                                        @result.CaseId
                                    </td>
                                    <td>
                                        @result.PolicyNo
                                    </td>
                                    <td>
                                        @result.ClaimNo
                                    </td>
                                    <td>
                                        @result.Source
                                    </td>
                                    <td>
                                        @result.WorkType
                                    </td>
                                    <td>
                                        @result.SLAClaim 
                                    </td>
                                    <td>
                                        @result.SLAPending
                                    </td>
                                    <td>
                                        @result.UserFrom
                                    </td>
                                    <td>
                                        @result.RequestPendingDate
                                    </td>
                                    <td>
                                        @result.RLSTRANS
                                    </td>
                                    <td>
                                        @result.RLSCaptureDate
                                    </td>
                                    <td>
                                        @result.CreatedDate
                                    </td>
                                    <td>
                                        @result.ReceivedDate
                                    </td>
                                    <td>
                                        @result.VIP
                                    </td>
                                    <td>
                                        @result.Message
                                    </td>
                                </tr>
                                seq++;
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
}
<script src="~/Scripts/CountDown/countdown.login.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true,
            paging: true
        });

        var dttbl = '@Url.Content("~/")Datatable';
    });

    $("#dtreceiveddatefrom").datetimepicker({
        viewMode: 'days',
        format: 'yyyy-MM-dd',
        changeMonth: true,
        changeYear: false
    }).on('changeDate', function () {
        $('.bootstrap-datetimepicker-widget.dropdown-menu').hide();
    });

    $("#dtreceiveddateto").datetimepicker({
        viewMode: 'days',
        format: 'yyyy-MM-dd',
        changeMonth: true,
        changeYear: false
    }).on('changeDate', function () {
        $('.bootstrap-datetimepicker-widget.dropdown-menu').hide();
    });
</script>