app/ReportingImage/Controllers/DipcadClaimPOSAssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using ReportingImage.Models;
using ReportingImage.App_Start;
using ReportingImage.ViewModels;
using System.IO;
using iTextSharp.text;
using System.Drawing;
using System.Drawing.Imaging;
using Ionic.Zip;

namespace ReportingImage.Controllers
{
    public class DipcadClaimPOSAssignController : Controller
    {
        ReportingImageEntities _db = new ReportingImageEntities();
        GetSession MeGetSession = new GetSession();

        //[CheckAuthorize(Roles = "Case List")]
        // GET: POSAssign
        public ActionResult Index()
        {
            var User = GetSession.UserName();

            var modelPolicyPool = new ListPosPolicyPoolViewModels() { ListPosPolicyPoolOpenViewModels = new List<PosPolicyPoolOpenViewModels>() };
            //var modelPolicyPool = new ListPosPolicyPoolViewModels()
            //{
            //     ListPosPolicyPoolOpenViewModels = GetPolicyPoolList("", "", "", "0","","", 1)
            //};

            #region ' data basic '
            List<SelectListItem> dataAssignTo = new List<SelectListItem>();
            dataAssignTo.Add(new SelectListItem() { Text = null, Value = "" });
            var users = GetUserPOS();
            if (users != null)
            {
                foreach (var item in users)
                { dataAssignTo.Add(new SelectListItem() { Text = item.username, Value = item.username }); }
            }
            ViewBag.ddlAssignTo = new SelectList(dataAssignTo, "Value", "Text", null);

            // assign in search
            ViewBag.ddl2AssignTo = new SelectList(dataAssignTo, "Value", "Text", null);
            #endregion

            return View(modelPolicyPool);
        }

        [HttpPost]
        //[CheckAuthorize(Roles = "Case List")]
        public ActionResult Index(ListPosPolicyPoolViewModels models, string Submit, string ddlAssignTo, string assignTo, string txbDateFrom, string txbDateTo, string remarks, string policyNumber, int pageNumber = 1)
        {
            TempData["AssignTo"] = assignTo;

            int count = 0;
            string cek = string.Empty;
            string errorstr = string.Empty;
            string success = string.Empty;
            string user = "";
            int ceknotRR = 0;
            DataTable result;

            #region submit POS Assign
            /*
            //if (Submit == "Submit")
            //{
            //    if (models.ListPosPolicyPoolOpenViewModels == null)
            //    {
            //        TempData["Error"] = $"Data Not Found";
            //        goto ShowList;
            //    }
            //    user = GetSession.UserName();
            //    foreach (PosPolicyPoolOpenViewModels item in models.ListPosPolicyPoolOpenViewModels)
            //    {
            //        if (item.CHECKED)
            //        {
            //            if (item.METHOD != "RR" && (ddlAssignTo == null ? "" : ddlAssignTo).Length > 0)
            //            {
            //                result = Common.ExecuteQuery($"dbo.sp_POS_Submit {item.CASE_ID},'{item.CIF}','{item.POLICY_NO}','','','SYS ASSIGN','{ddlAssignTo}','{remarks}','0',''");
            //                cek = result.Rows[0][0].ToString();
            //                if (cek != "SUCCESS")
            //                {
            //                    if (string.IsNullOrEmpty(errorstr))
            //                    {
            //                        errorstr = $"Case ID ({item.CASE_ID}) {cek} <br>";
            //                    }
            //                    else
            //                    { errorstr += $"Case ID ({item.CASE_ID}) {cek} <br>"; }
            //                    count--;
            //                }
            //                else
            //                { ceknotRR++; }
            //            }
            //            else
            //            {
            //                result = Common.ExecuteQuery($"dbo.sp_POS_RR_assign 'SYS ASSIGN',{item.CASE_ID},'{remarks}'");
            //                cek = result.Rows[0][0].ToString();
            //                if (cek.Contains("Error"))
            //                {
            //                    if (string.IsNullOrEmpty(errorstr))
            //                    {
            //                        errorstr = $"RR Case ID ({item.CASE_ID}) {cek} <br>";
            //                    }
            //                    else
            //                    { errorstr += $"RR Case ID ({item.CASE_ID}) {cek} <br>"; }
            //                    count--;
            //                }
            //                else
            //                {
            //                    if (string.IsNullOrEmpty(success))
            //                    {
            //                        success = $"RR Case ID {item.CASE_ID} to {cek} <br>";
            //                    }
            //                    else
            //                    {
            //                        success += $"RR Case ID {item.CASE_ID} to {cek} <br>";
            //                    }
            //                }
            //            }
            //            count++;
            //        }
            //    }

            //    if (!string.IsNullOrEmpty(errorstr))
            //    {
            //        TempData["Error"] = $"Please check before submit";
            //        goto ShowList;
            //    }

            //    if (count > 0)
            //    {
            //        if (ceknotRR > 0)
            //        {
            //            success = string.IsNullOrEmpty(success) ? "" : success;
            //            success += $"Success Assign To {ddlAssignTo} ";
            //        }
            //        TempData["Success"] = success.Trim();
            //    }

            //    _db.zsp_AuditTrailInsert("Assign To", null, user);
            //}
            //else
            //{
            //    //if (txbDateFrom == "" || txbDateTo == "")
            //    //{
            //    //    TempData["Error"] = $"Choose Date From and To";
            //    //    goto ShowList;
            //    //}
            //}
            */
            #endregion

            user = GetSession.UserName();

        //ShowList:

            ModelState.Clear();
            var modelPolicyPool = new ListPosPolicyPoolViewModels()
            {
                ListPosPolicyPoolOpenViewModels = GetPolicyPoolList(assignTo, policyNumber, "", "", "0", txbDateFrom, txbDateTo, 1)
            };

            #region ' data basic '
            List<SelectListItem> dataAssignTo = new List<SelectListItem>();
            dataAssignTo.Add(new SelectListItem() { Text = null, Value = "" });
            var users = GetUserPOS();
            if (users != null)
            {
                foreach (var item in users)
                { dataAssignTo.Add(new SelectListItem() { Text = item.username, Value = item.username }); }
            }
            ViewBag.ddlAssignTo = new SelectList(dataAssignTo, "Value", "Text", null);

            // assign in search
            ViewBag.ddl2AssignTo = new SelectList(dataAssignTo, "Value", "Text", assignTo);

            List<SelectListItem> listMethod = new List<SelectListItem>();
            listMethod.Add(new SelectListItem() { Text = "Direct", Value = "Direct" });
            listMethod.Add(new SelectListItem() { Text = "RR", Value = "RR" });
            ViewBag.ddlMethod = new SelectList(listMethod, "Value", "Text", null);

            TempData["txbDateFrom"] = txbDateFrom;
            TempData["txbDateTo"] = txbDateTo;
            #endregion

            return View(modelPolicyPool);
        }

        Byte[] fileByte;
        //[CheckAuthorize(Roles = "Images Client POS")]
        public ActionResult ImagesClient(int case_id)
        {
            string sourcePathTmp = string.Empty;
            string sourcePath = string.Empty;
            string filePath = string.Empty;
            var extension = string.Empty;

            POSListImageViewModel model = new POSListImageViewModel();
            List<DetailImageViewModels> images = new List<DetailImageViewModels>();
            //var imagesList = _db.sp_POS_Images(case_id, GetSession.UserName());
            List<ImageResult> imagesList = new List<ImageResult>();

            DataTable dTab = Common.ExecuteQuery($"dbo.SPInq_CLM_Images '{case_id}',''");
            int counter = dTab.Rows.Count;
            for (int i = 0; i < dTab.Rows.Count; i++)
            {
                imagesList.Add(new ImageResult()
                {
                    POLICYNO = dTab.Rows[i]["POLICYNO"].ToString(),
                    FILENAMEORIGIN = dTab.Rows[i]["FILENAMEORIGIN"].ToString(),
                    FILENAME = dTab.Rows[i]["FILENAME"].ToString(),//.Replace(" ", "_"),
                    DOCUMENTNAME = dTab.Rows[i]["DOCUMENTNAME"].ToString(),
                    SOURCE = dTab.Rows[i]["SOURCE"].ToString(),
                    FILEIMAGE = (Byte[])dTab.Rows[i]["FILEIMAGE"],
                    CREATEDATE = Convert.ToDateTime(dTab.Rows[i]["CREATEDATE"].ToString()),
                });
            }

            foreach (var item in imagesList)
            {
                sourcePathTmp = Server.MapPath("~/Files/" + item.POLICYNO);
                sourcePath = Server.MapPath("~/Files/" + item.POLICYNO + "/");
                if (!Directory.Exists(sourcePath))
                {
                    Directory.CreateDirectory(sourcePath);
                }
                else
                {
                    filePath = sourcePath + item.FILENAME;
                    System.IO.File.Delete(filePath);
                }

                if (Common.GetStringRight(item.FILENAME, 3) == "tif" || Common.GetStringRight(item.FILENAME, 4) == "tiff")
                {

app/ReportingImage/Views/DipcadClaimPOSAssign/ImagesClient.cshtml
@model ReportingImage.ViewModels.POSListImageViewModel

@{
    ViewBag.Title = "Detail Image";
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-warning">
        <p><strong>Error:</strong> @TempData["Error"].ToString()</p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @TempData["Success"].ToString()
    </div>

}

@using (Html.BeginForm("ImagesClient", "POSOpen"))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-6">List Images</div>
                <div class="col-lg-6" style="text-align:right">
                    <a data-toggle="modal" href="~/POSOpen" class="btn btn-primary"><i class="fa fa-backward"></i> Back </a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <table width="100%" style="font-size:12px" class="table table-striped table-bordered table-hover" id="dataTable-example">
                        <thead>
                            <tr>
                                <th><input type="checkbox" onchange="checkAll(this)" /></th>
                                <th>@Html.DisplayName("File Name")</th>
                                <th>@Html.DisplayName("Document Name")</th>
                                <th>@Html.DisplayName("Create Date")</th>
                                <th>@Html.DisplayName("Source")</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.DetailImageViewModels.Count; ++i)
                            {
                                <tr>
                                    <td>
                                        @Html.CheckBoxFor(x => x.DetailImageViewModels[i].Checked)
                                        @Html.HiddenFor(x => x.DetailImageViewModels[i].PolicyNumber)
                                    </td>
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILENAME)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILEIMAGE_temp)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].Extension)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].DocumentName)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].Source)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILENAMEORIGIN)
                                    <td>
                                        <button class="btn btn-default" type="button" data-toggle="modal" data-target="#@Model.DetailImageViewModels[i].PreviewContentId">
                                            @Model.DetailImageViewModels[i].FILENAME
                                        </button>

                                        <!--MODAL Show File-->
                                        <div id="@Model.DetailImageViewModels[i].PreviewContentId" class="modal fade" role="dialog" style="width:unset; background-color: transparent">
                                            <div class="modal-dialog" style="width:800px">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        <h4 class="modal-title" style="background-color:none">Preview Content</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        @if (Model.DetailImageViewModels[i].Extension == "application/pdf")
                                                        {
                                                            <object type="@Model.DetailImageViewModels[i].Extension" data="@Model.DetailImageViewModels[i].FilePath"
                                                                    width="750" height="500"></object>
                                                        }
                                                        else
                                                        {
                                                            <img src="@Model.DetailImageViewModels[i].FilePath"
                                                                 width="750" height="500" />
                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                
                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].DocumentName)</td>
                               
                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].CreatedDate)</td>
                                
                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].Source)</td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <!--Button Download-->
            @Html.HiddenFor(x => x.Case_ID)
            @Html.HiddenFor(x => x.PolicyNumber)
            @Html.HiddenFor(x => x.WorkType_id)
            <div class="row">
                <div class="col-lg-12">
                    <div class="box-footer">
                        <button id="btnSubmit" type="submit" class="btn btn-default"><i class="fa fa-download"></i> Download Zip File</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/CountDown/countdown.login.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTable-example').DataTable({
            responsive: true,
            paging: false
        });
    });

    function checkAll(elm) {
        var checkBoxes = document.getElementsByTagName('input');
        if (elm.checked) {
            for (var i = 0; i < checkBoxes.length; i++) {
                if (checkBoxes[i].type == 'checkbox') {
                    checkBoxes[i].checked = true;
                }
            }
        }
        else {
            for (var i = 0; i < checkBoxes.length; i++) {
                if (checkBoxes[i].type == 'checkbox') {
                    checkBoxes[i].checked = false;
                }
            }
        }
    };
</script>

app/ReportingImage/Views/DipcadClaimPOSAssign/Index.cshtml
@model ReportingImage.ViewModels.ListPosPolicyPoolViewModels

@{
    ViewBag.Title = "Case List";
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-warning">
        <p><strong>Error:</strong> @TempData["Error"].ToString()</p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @Html.Raw(@TempData["Success"].ToString())
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-2">
                    Date From
                </div>
                <div class="col-lg-4">
                    <div id="dateFrom" class="input-group">
                        @Html.TextBox("txbDateFrom", null, new { @placeholder = "Date From", @class = "form-control" })
                        <span class="input-group-addon add-on ">
                            <i data-time-icon="fa fa-calendar" data-date-icon="fa fa-calendar"></i>
                        </span>
                    </div>
                    @*<label id="errorDateFrom" class="text-danger" hidden="hidden">This field is required</label>*@
                </div>
                <div class="col-lg-2">
                    Date To
                </div>
                <div class="col-lg-4">
                    <div id="dateTo" class="input-group">
                        @Html.TextBox("txbDateTo", null, new { @placeholder = "Date To", @class = "form-control" })
                        <span class="input-group-addon add-on ">
                            <i data-time-icon="fa fa-calendar" data-date-icon="fa fa-calendar"></i>
                        </span>
                    </div>
                    @*<label id="errorDateTo" class="text-danger" hidden="hidden">This field is required</label>*@
                </div>
            </div>
            <div class="row" style="margin-top: 10px">
                <div class="col-lg-2">
                    Policy Number
                </div>
                <div class="col-lg-10">
                    @Html.TextBox("policyNumber", null, new { @placeholder = "Policy Number", @class = "form-control" })
                </div>
            </div>
            <div class="row" style="margin-top: 10px">
                <div class="col-lg-2">
                    User Assign
                </div>
                <div class="col-lg-10">
                    @Html.DropDownList("AssignTo", (SelectList)ViewBag.ddl2AssignTo, new
               {
                   @class = "form-control"
               })
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-lg-offset-2 col-lg-10">
                    <input id="btnSearch" type="submit" value="Search" name="Submit" class="btn btn-primary" onclick="return ValidationFilter()" />
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    @*@Html.HiddenFor(x => x.ListPosPolicyPoolOpenViewModels)*@
                    <table width="100%" style="font-size:12px" class="table table-striped table-bordered table-hover" id="dataTable-example">
                        <thead>
                            <tr>
                                <th><input type="checkbox" onchange="checkAll(this)" /></th>
                                <th>
                                    @Html.DisplayName("Action")
                                </th>
                                <th>
                                    @Html.DisplayName("Case ID")
                                </th>
                                <th>
                                    @Html.DisplayName("Policy Number")
                                </th>
                                <th>
                                    @Html.DisplayName("CIF")
                                </th>
                                <th>
                                    @Html.DisplayName("Source")
                                </th>
                                <th>
                                    @Html.DisplayName("Work Type")
                                </th>
                                <th hidden>
                                    @Html.DisplayName("Category")
                                </th>
                                <th>
                                    @Html.DisplayName("RLS Trans Status")
                                </th>
                                <th>
                                    @Html.DisplayName("Created Date")
                                </th>
                                <th>
                                    @Html.DisplayName("RLS Captured Date")
                                </th>
                                <th>
                                    @Html.DisplayName("Bucket")
                                </th>
                                <th>
                                    @Html.DisplayName("Method")
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.ListPosPolicyPoolOpenViewModels.Count; ++i)
                            {
                                <tr>
                                    <td>
                                        @Html.CheckBoxFor(x => x.ListPosPolicyPoolOpenViewModels[i].CHECKED, htmlAttributes: new { @onchange = "ValidationMethod(this)" })
                                    </td>
                                    <td>
                                        <a data-toggle="tooltip" title="Image"
                                           href="@Url.Action("ImagesClient","DipcadClaimPOSAssign",new { case_id = Model.ListPosPolicyPoolOpenViewModels[i].CASE_ID })"
                                           class="btn btn-default">
                                            <i class="fa fa-file-image-o"></i>
                                        </a>
                                    </td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].CASE_ID)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].POLICY_NO)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].CIF)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].SOURCE)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].WORKTYPE)</td>
                                    <td hidden>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].CATEGORY)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].RLS_TRANS)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].CREATE_DATE)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].RLS_CAPTURE_DATE)</td>
                                    <td>@Html.DisplayFor(x => x.ListPosPolicyPoolOpenViewModels[i].BUCKET)</td>
                                    <td>

                                        @Html.DropDownListFor(x => x.ListPosPolicyPoolOpenViewModels[i].METHOD,
                                                (SelectList)ViewBag.ddlMethod, htmlAttributes: new { @class = "form-control", @style = "display: none;" })

                                    </td>
                                    @Html.HiddenFor(x => x.ListPosPolicyPoolOpenViewModels[i].CASE_ID)
                                    @Html.HiddenFor(x => x.ListPosPolicyPoolOpenViewModels[i].POLICY_NO)
                                    @Html.HiddenFor(x => x.ListPosPolicyPoolOpenViewModels[i].CIF)

                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            Action
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-2">
                    Assign To
                </div>
                <div class="col-lg-10">
                    @Html.DropDownList("ddlAssignTo", (SelectList)ViewBag.ddlAssignTo, htmlAttributes: new { @class = "form-control", @placeholder = "-Select-", @disabled = "disabled" })
                    <label id="errorddlAssignTo" class="text-danger" hidden="hidden">This field is required</label>
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-lg-2">
                    Remarks
                </div>
                <div class="col-lg-10">
                    @Html.TextArea("remarks", htmlAttributes: new { @class = "form-control", @style = "width:100%;height:100px", @disabled = "disabled" })
                </div>
            </div>
            <!--Button Submit-->
            <div class="row" style="margin-top:10px">
                <div class="col-lg-offset-2 col-lg-10">
                    <div class="box-footer">
                        <input id="btnSearch" type="submit" value="Submit" name="Submit" class="btn btn-primary" onclick="return ValidationAssign()" disabled/>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/CountDown/countdown.login.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTable-example').DataTable({
            responsive: true,
            paging: false
        });
    });
    $("#dateFrom").datetimepicker({
        viewMode: 'days',
        format: 'yyyy-MM-dd',
        changeMonth: true,
        changeYear: false
    }).on('changeDate', function () {
        $('.bootstrap-datetimepicker-widget.dropdown-menu').hide();

    });
    $("#dateTo").datetimepicker({
        viewMode: 'days',
        format: 'yyyy-MM-dd',
        changeMonth: true,
        changeYear: false
    }).on('changeDate', function () {
        $('.bootstrap-datetimepicker-widget.dropdown-menu').hide();

    });

    function checkAll(elm) {
        //var checkBoxes = document.getElementsByTagName('input');
        //if (elm.checked) {
        //    for (var i = 0; i < checkBoxes.length; i++) {
        //        if (checkBoxes[i].type == 'checkbox') {
        //            checkBoxes[i].checked = true;
        //            ValidationMethod(checkBoxes[i]);
        //        }
        //    }
        //}
        //else {
        //    for (var i = 0; i < checkBoxes.length; i++) {
        //        if (checkBoxes[i].type == 'checkbox') {
        //            checkBoxes[i].checked = false;
        //            ValidationMethod(checkBoxes[i]);
        //        }
        //    }
        //}
    };
    function ValidationMethod(elm) {
        //var idx = $(elm).closest("tr").index() + 1;
        //var cbox = $('tr:eq(' + idx + ') td:eq(11) select');
        //if (elm.checked) {
        //    cbox.show();
        //} else {
        //    cbox.hide();
        //}
    }

    function ValidationFilter() {
        //document.getElementById("errorDateFrom").style.display = 'none';
        //document.getElementById("errorDateTo").style.display = 'none';
        //var status = true;
        //if ($("#txbDateFrom").val() == '') {
        //    document.getElementById("errorDateFrom").style.display = 'block';
        //    status = false;
        //}
        //if ($("#txbDateTo").val() == '') {
        //    document.getElementById("errorDateTo").style.display = 'block';
        //    status = false;
        //}
        //return status;
    }
    function ValidationAssign() {
        //document.getElementById("errorddlAssignTo").style.display = 'none';
        //var status = true;
        //if ($("#ddlAssignTo").val() == '') {
        //    document.getElementById("errorddlAssignTo").style.display = 'block';
        //    return false;
        //}
    }
</script>