app/ReportingImage/Controllers/DipcadClaimAssignController.cs
using Ionic.Zip;
using iTextSharp.text;
using ReportingImage.Models;
using ReportingImage.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ReportingImage.Controllers
{
    public class DipcadClaimAssignController : Controller
    {
        ReportingImageEntities _db = new ReportingImageEntities();
        GetSession MeGetSession = new GetSession();
        string thisMenu = "Assignlist";

        // GET: DipcadClaimAssign
        public ActionResult Index()
        {
            var User = GetSession.UserName();


            //bool SearchCounter = false;
            //var tempResult = _db.SPCLM_PolicyPool_Inq().ToList();
            
            var cektempResult = new SPCLM_PolicyPool_Inq_Result();
            cektempResult.Message = "";
            var newcektempResult = new List<SPCLM_PolicyPool_Inq_Result>();

            ViewBag.ListPolicyPool = newcektempResult;
            //var modelPolicyPool = new List<DipcadClaimOpenViewModels>();
            var modelPolicyPool = new ListDipcadClaimPoolViewModels()
            {
                ListDipcadClaimPoolOpenViewModels = new List<DipcadClaimOpenViewModels>()
            };

            #region ' data basic '
            List<SelectListItem> dataAssignTo = new List<SelectListItem>();
            dataAssignTo.Add(new SelectListItem() { Text = null, Value = "" });
            dataAssignTo.Add(new SelectListItem() { Text = "System RR", Value = "SystemRR" });
            List<SelectListItem> userSubmitAssignList = new List<SelectListItem>();
            userSubmitAssignList.Add(new SelectListItem() { Text = null, Value = "" });
            var users = GetUserCLM();
            if (users != null)
            {
                foreach (var item in users)
                {
                    //if (item.username == GetSession.UserName()) continue;
                    dataAssignTo.Add(new SelectListItem() { Text = item.username, Value = item.username });
                    userSubmitAssignList.Add(new SelectListItem() { Text = item.username, Value = item.username });
                }
            }
            // assign in search field
            dataAssignTo = dataAssignTo.Where(x => x.Value != "SystemRR").ToList();
            ViewBag.ddl2AssignTo = new SelectList(dataAssignTo, "Value", "Text");
            
            // assign in submit field            
            // asso tidak boleh manggil sesama asso di role with config PreventAssoClaimAssignList
            var cekAssoConfig = GetReferenceConfig("PreventAssoClaimAssignList");
            //var userSubmitAssignList = dataAssignTo;
            var cekEmployee = GetUserClaimAll();
            var cekUserPrevilage = GetUserPrevilage();

            if (cekAssoConfig.Count > 0)
            {
                for (int i = 0; i < dataAssignTo.Count(); i++)
                {
                    for (int j = 0; j < cekEmployee.Count(); j++)
                    {
                        if (dataAssignTo[i].Value == cekEmployee[j].username)
                        {
                            //loop for checking prevent role
                            for (int k = 0; k < cekAssoConfig.Count(); k++)
                            {
                                if (cekEmployee[j].previlage_name.Trim().Contains(cekAssoConfig[k]))
                                {
                                    if (cekUserPrevilage.previlage_name == cekEmployee[j].previlage_name)
                                        userSubmitAssignList.RemoveAll(x => x.Value == dataAssignTo[i].Value);
                                }
                            }
                        }
                    }
                }
            }            
            ViewBag.ddlAssignTo2 = new SelectList(userSubmitAssignList, "Value", "Text");

            


            string[] statusType;
            List<SelectListItem> dataStatus = new List<SelectListItem>();
            var DipcadStatus = GetReferenceData("DipcadStatus");
            dataStatus.Add(new SelectListItem() { Text = "", Value = "" });
            if (DipcadStatus != null)
            {
                foreach (string item in DipcadStatus)
                {
                    statusType = item.Split('|');
                    dataStatus.Add(new SelectListItem() { Text = statusType[1], Value = statusType[0] });
                }
            }
            ViewBag.Status = new SelectList(dataStatus, "Value", "Text");

            string[] wType;
            List<SelectListItem> dataWorkType = new List<SelectListItem>();
            var workTypeList = GetListWorkType();
            dataWorkType.Add(new SelectListItem() { Text = "", Value = "" });
            if (workTypeList != null)
            {
                foreach (string item in workTypeList)
                {
                    wType = item.Split('|');
                    dataWorkType.Add(new SelectListItem() { Text = wType[1], Value = wType[1] });
                }
            }
            ViewBag.dllWorktype = new SelectList(dataWorkType, "Value", "Text");

           
            bool submitControl = true;

            if (cekUserPrevilage != null)
            {
                if (cekUserPrevilage.dept_id != "CLAIM")
                {
                    //foreach (var item in cekAsso)
                    //{
                    //    if (item.username == GetSession.UserName())
                    //    {
                    //        submitControl = false;
                    //        break;
                    //    }
                    //}
                    submitControl = false;
                }
            }
            else
                submitControl = false;

            ViewBag.SubmitControl = submitControl == true ? "1" : "0";
            #endregion

            return View(modelPolicyPool);
        }

        [HttpPost]
        //[CheckAuthorize(Roles = "Case List")]
        //public ActionResult Index(ListDipcadClaimPoolViewModels models, string Submit, string policyNumber, string ddlCategory, int pageNumber = 1, string receiveddatefrom = null, string receiveddateto = null, string AssignTo = null, string ddlAssignTo = null, string remarks = null)
        public ActionResult Index(ListDipcadClaimPoolViewModels models, string Submit, string policyNumber, string ddlCategory, int pageNumber = 1, string receiveddatefrom = null, string receiveddateto = null, string AssignTo = null, string ddlAssignTo = null, string remarks = null, string Status = null, string Worktype = null)

        {
            TempData["AssignTo"] = AssignTo;

            int count = 0;
            string cek = string.Empty;
            string errorstr = string.Empty;
            string success = string.Empty;
            string user = "";
            int ceknotRR = 0;
            DataTable result;           

            if (Submit == "Submit")
            {
                if (models.ListDipcadClaimPoolOpenViewModels == null)
                {
                    TempData["Error"] = $"Data Not Found";
                    goto ShowList;
                }
                user = GetSession.UserName();
                foreach (DipcadClaimOpenViewModels item in models.ListDipcadClaimPoolOpenViewModels)
                {
                    if (item.CHECKED)
                    {
                        if (ddlAssignTo == "SystemRR")
                        {
                            try
                            {
                                //update user assign to null
                                DataTable dTab = Common.ExecuteQuery($"update clm_policy_pool set userassign = null where caseid = '{item.CASE_ID}'");
                                //insert table history
                                DataTable insertTab = Common.ExecuteQuery($"insert into clm_Job_History (CASEID,POLICYNO,JOB,USERFROM,USERTO,DATESET) values('{item.CASE_ID}', '{item.POLICY_NO}', 'RR_ASSIGN', '{GetSession.UserName()}', 'RRPROSES', GETDATE())");
                                //run RR proses
                                DataTable RRexec = Common.ExecuteQuery($"SPRR_CLM_Policy_Pool");
                            }
                            catch (Exception ex)
                            {
                                if (string.IsNullOrEmpty(errorstr))
                                {
                                    errorstr = $"Case ID ({item.CASE_ID}) {cek} <br>";
                                }
                                else
                                { errorstr += $"Case ID ({item.CASE_ID}) {cek} <br>"; }
                                count--;
                            }
                        }
                        if ((ddlAssignTo == null ? "" : ddlAssignTo).Length > 0 && ddlAssignTo != "" && ddlAssignTo != "SystemRR")
                        {
                            string iscomplete = Convert.ToString(item.IS_COMPLETE).ToLower() == "false" ? "0" : "1";

                            //result = Common.ExecuteQuery($"dbo.sp_POS_Submit {item.CASE_ID},'{item.CIF}','{item.POLICY_NO}','','','SYS ASSIGN','{ddlAssignTo}','{remarks}','0',''");
                            //result = Common.ExecuteQuery($"dbo.SPUpd_CLM_Submit '{item.CASE_ID}','{item.POLICY_NO}','','{iscomplete}','','','','','{ddlAssignTo}','','{remarks}','','','SYS ASSIGN'");
                                                       
                            result = Common.ExecuteQuery($"dbo.SPUpd_CLM_RR_Assign '{GetSession.UserName()}','{ddlAssignTo}',{item.CASE_ID},'{remarks}'");


                            cek = result.Rows[0][0].ToString();
                            if (cek != "SUCCESS")
                            {
                                if (string.IsNullOrEmpty(errorstr))
                                {

app/ReportingImage/Views/DipcadClaimAssign/ImagesClient.cshtml
@model ReportingImage.ViewModels.DipcadClaimListImageViewModel

@{
    ViewBag.Title = "Detail Image";
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-warning">
        <p><strong>Error:</strong> @TempData["Error"].ToString()</p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @TempData["Success"].ToString()
    </div>

}

@using (Html.BeginForm("ImagesClient", "DipcadClaimAssign", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-6">List Images</div>
                <div class="col-lg-6" style="text-align:right">
                    <a data-toggle="modal" href="@Url.Action("Index","DipcadClaimAssign")" class="btn btn-primary"><i class="fa fa-backward"></i> Back </a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">

                <div class="col-md-2">
                    <input id="btnAddImage" class="btn btn-primary" value="Add Image" type="button" data-toggle="modal" data-target="#myModal" disabled/>@*onclick="return ValidationSubmit()" />*@
                </div>

                <div id='myModal' class='modal fade' role="dialog" style="width:unset; background-color: transparent">
                    <div class="modal-dialog" style="width:800px">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title" style="background-color:none">Preview Content</h4>
                            </div>
                            <div class="modal-body">
                                @{
                                    <div class="row" style="margin-top:10px">
                                        <div class="col-md-3" style="text-align:right">
                                            Document Type
                                        </div>
                                        <div class="col-md-9">
                                            @Html.DropDownList("dllDocType", (SelectList)ViewBag.dllDocType, htmlAttributes: new { @class = "form-control", @placeholder = "-- Select --" })
                                            <label id="errorDocumentType" class="text-danger" hidden="hidden">This field is required</label>
                                        </div>
                                    </div>

                                    <div class="row" style="margin-top:10px">
                                        <div class="col-md-3" style="text-align:right">
                                            Description
                                        </div>
                                        <div class="col-md-9">
                                            @*@Html.DropDownList("ddlDocumentType", (SelectList)ViewBag.dllDocumentType, new { @class = "form-control" })*@
                                            @Html.TextBox("description", new { @class = "form-control", @placeholder = "Description", })
                                            @*@Html.TextBoxFor(model => model.CLAIMNO, new { @class = "form-control" })*@
                                            <label id="errorDocumentType" class="text-danger" hidden="hidden">This field is required</label>
                                        </div>
                                    </div>

                                    <div class="row" style="margin-top:10px">
                                        <div class="col-md-3" style="text-align:right">
                                            Chosse File
                                        </div>
                                        <div class="col-md-9">
                                            @Html.TextBox("mdlImageFile", null, new { @type = "file", @name = "File", @accept = ".pdf,.jpg,.jpeg,.tiff,.tif" })
                                            <label id="errorImageFile" class="text-danger" hidden="hidden">This field is required</label>
                                        </div>
                                    </div>
                                }
                                <div class="row" style="margin-top:10px">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Add Image" name="Submit" class="btn btn-primary" />@*id="btnModalSubmit"*@ @*onclick="return ValidationModel()" />*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-12">
                    <table width="100%" style="font-size:12px" class="table table-striped table-bordered table-hover" id="dataTable-example">
                        <thead>
                            <tr>
                                <th><input type="checkbox" onchange="checkAll(this)" /></th>
                                <th>@Html.DisplayName("File Name")</th>
                                <th>@Html.DisplayName("Document Name")</th>
                                <th>@Html.DisplayName("Description")</th>
                                <th>@Html.DisplayName("Create Date")</th>
                                <th>@Html.DisplayName("Source")</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.DetailImageViewModels.Count; ++i)
                            {
                                <tr>
                                    <td>
                                        @Html.CheckBoxFor(x => x.DetailImageViewModels[i].Checked)
                                        @Html.HiddenFor(x => x.DetailImageViewModels[i].PolicyNumber)
                                    </td>
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILENAME)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILEIMAGE_temp)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].Extension)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].DocumentName)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].Source)
                                    @Html.HiddenFor(x => x.DetailImageViewModels[i].FILENAMEORIGIN)
                                    <td>
                                        <button class="btn btn-default" type="button" data-toggle="modal" data-target="#@Model.DetailImageViewModels[i].PreviewContentId">
                                            @Model.DetailImageViewModels[i].FILENAME
                                        </button>

                                        <!--MODAL Show File-->
                                        <div id="@Model.DetailImageViewModels[i].PreviewContentId" class="modal fade" role="dialog" style="width:unset; background-color: transparent">
                                            <div class="modal-dialog" style="width:800px">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        <h4 class="modal-title" style="background-color:none">Preview Content</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        @if (Model.DetailImageViewModels[i].Extension == "application/pdf")
                                                        {
                                                            <object type="@Model.DetailImageViewModels[i].Extension" data="@Model.DetailImageViewModels[i].FilePath"
                                                                    width="750" height="500"></object>
                                                        }
                                                        else
                                                        {
                                                            <img src="@Model.DetailImageViewModels[i].FilePath"
                                                                 width="750" height="500" />
                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].DocumentName)</td>

                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].Description)</td>

                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].CreatedDate)</td>

                                    <td>@Html.DisplayFor(x => x.DetailImageViewModels[i].Source)</td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <!--Button Download-->
            @Html.HiddenFor(x => x.Case_ID)
            @Html.HiddenFor(x => x.PolicyNumber)
            @Html.HiddenFor(x => x.WorkType_id)
            <div class="row">
                <div class="col-lg-12">
                    <div class="box-footer">
                        <button id="btnSubmit" type="submit" class="btn btn-default"><i class="fa fa-download"></i> Download Zip File</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/CountDown/countdown.login.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTable-example').DataTable({
            responsive: true,
            paging: false
        });
    });

    function checkAll(elm) {
        var checkBoxes = document.getElementsByTagName('input');
        if (elm.checked) {
            for (var i = 0; i < checkBoxes.length; i++) {
                if (checkBoxes[i].type == 'checkbox') {
                    checkBoxes[i].checked = true;
                }
            }
        }
        else {
            for (var i = 0; i < checkBoxes.length; i++) {
                if (checkBoxes[i].type == 'checkbox') {
                    checkBoxes[i].checked = false;
                }
            }
        }
    };
</script>